.TH PAGEMON 1 "October 2024" "Version 1.0.1" "PageMon Manual"
.SH NAME
PageMon \- Monitors specified websites for changes and sends notifications.

.SH SYNOPSIS
.B pagemon
[\fIurl\fR...] [\fIoptions\fR]

.SH DESCRIPTION
.B PageMon
is a script that monitors specified websites for changes and sends notifications when changes are detected.

.SH OPTIONS
.TP
.B \-h, \--help
Display this help message.
.TP
.B \-V, \--version
Display the script version.
.TP
.B \-f, \--url-file \fIfile\fR
Specify a file containing a list of URLs to monitor. (default: ~/.pagemon_urls)
.TP
.B \-i, \--interval \fIminutes\fR
Set the interval between checks (default is 5 minutes).
.TP
.B \-t, \--threshold \fIpercentage\fR
Set the threshold percentage for detecting changes. Higher values mean fewer notifications for minor changes. (default: 5%)
.TP
.B \-c, \--config \fIconfig_file\fR
Specify a custom configuration file. (default: ~/.pagemonrc)
.TP
.B \-I, \--init
Initialize the configuration file.
.TP
.B \-s, \--show-config
Show the configuration settings.
.TP
.B \-S, \--show-config-file
Show the configuration file.
.TP
.B \-U, \--list-urls
List all watched URLs.
.TP
.B \-C, \--clean
Delete all cached files.
.TP
.B \-b, \--background
Run the script in the background.
.TP
.B \-p, \--pushover
Send Pushover notifications.
.TP
.B \-a, \--api-token \fItoken\fR
Specify the API token for Pushover notifications.
.TP
.B \-u, \--user-key \fIkey\fR
Specify the user key for Pushover notifications.
.TP
.B \-d, \--desktop
Send desktop notifications using AppleScript.
.TP
.B \-v, \--verbose
Enable verbose output.
.TP
.B \-l, \--log
Log the log file to the screen.
.TP
.B \-o, \--output \fIfile\fR
Specify a custom log file location.
.TP
.B \-L, \--log-level \fIlevel\fR
Set the log level (FATAL, ERROR, WARN, INFO, DEBUG, TRACE).
.TP
.B \-K, \--killall
Kill all running instances of the script.
.TP
.B \-k, \--kill \fIpid\fR
Kill a specific instance of the script by PID.
.TP
.B \-P, \--list-pids
List all running instances of the script.

.SH EXAMPLES
.TP
.B pagemon http://example.com
Monitor the specified URL for changes.
.TP
.B pagemon \-f urls.txt
Monitor URLs listed in the specified file.
.TP
.B pagemon \-i 10
Set the interval between checks to 10 minutes.
.TP
.B pagemon \-t 10
Set the threshold percentage for detecting changes to 10%.
.TP
.B pagemon \-c custom_config.rc
Use a custom configuration file.
.TP
.B pagemon \-b
Run the script in the background.

.SH AUTHOR
John Smith III

.SH LICENSE
MIT License

.SH SEE ALSO
.BR curl (1),
.BR md5sum (1),
.BR sed (1),
.BR awk (1),
.BR xmllint (1),
.BR osascript (1)
